export type Locale = "es" | "en";

const CARTIER =
  "Jewels of the Jaguar is an independent, non-commercial artistic project inspired by a Cartier campaign. It was created solely as a creative exploration and portfolio piece and is not commissioned by, affiliated with, or endorsed by Cartier.";

export const CONTENT = {
  en: {
    nav: { work: "Work", services: "Services", resources: "Resources", about: "About", contact: "Contact", menu: "Menu", close: "Close" },
    skipToContent: "Skip to content",
    notFound: {
      eyebrow: "404",
      title: "This page doesn't exist.",
      body: "The page you're looking for may have moved or no longer exists.",
      ctaHome: "Back to Home",
      ctaWork: "View Work",
    },
    hero: {
      eyebrow: "Creative Director · Visual Artist",
      title: "Creative direction and visual art.",
      sub: "Visual concepts, image series and creative worlds for brands, spaces and cultural projects, with AI as one production tool.",
      viewWork: "View Selected Work",
      startProject: "Start a Project",
    },
    work: { label: "Selected Work", indexTitle: "Selected Work", indexIntro: "Four visual worlds. Concept, art direction and final imagery, developed end to end." },
    projectNav: { prev: "Previous project", next: "Next project", back: "Back to work", viewGallery: "View gallery", project: "Project", scroll: "Scroll to explore", concept: "The concept" },
    positioning: {
      title: "Not prompts. Creative direction.",
      body: "Concept development, art direction, visual production and careful selection, from first reference to final image. AI is one of the production tools, not the practice itself.",
    },
    services: {
      label: "Services",
      title: "Ways to work with me.",
      quote: "Custom quote",
      cta: "Start a Project",
      items: [
        { slug: "custom-visual", inquiry: "visual", secondary: false, name: "Custom Visual Projects", desc: "Concept, creative direction and visual production for brands, products and campaigns. I can develop the concept from scratch or execute an existing creative direction." },
        { slug: "print-creation", inquiry: "print", secondary: false, name: "Print Creation", desc: "Original artwork made for a space: one piece, several, or a cohesive series, developed from your references to final print-ready files." },
        { slug: "fine-art-prints", inquiry: "general", secondary: false, name: "Limited Fine Art Prints", desc: "Selected works from the series as limited-edition fine-art prints, 25 per size. Shipping charged separately." },
        { slug: "web-design", inquiry: "website", secondary: true, name: "Web Design & Development", desc: "Custom websites built around a strong visual direction, clear structure and a polished digital experience, from concept and design through implementation." },
      ],
    },
    about: {
      label: "About",
      body: "Luis Serrano is a creative director and visual artist. He develops visual concepts and image series for brands, spaces and cultural projects, drawing on a decade in brand and marketing that gives the work its structure and intent. AI is part of the production process, not the whole of it.",
    },
    contact: {
      title: "Have something in mind?",
      sub: "Tell me what you're building.",
      typeLabel: "What are you looking to create?",
      types: { visual: "Custom visual project", print: "Artwork for a space", website: "Website project", general: "Something else" },
      fields: {
        name: "Name", email: "Email", company: "Company / Brand",
        assets: "Number of assets", brief: "What are you looking to create?",
        timeline: "Timeline", budget: "Budget",
        space: "Space / room", dimensions: "Approx. dimensions",
        needs: "What do you need?", websiteUrl: "Existing website (if any)",
        pageCount: "Approx. page count", branding: "Do you already have branding / visual direction?",
        references: "References / links", message: "Message", optional: "optional",
      },
      opt: { yes: "Yes", no: "No", notSure: "Not sure", select: "Select" },
      submit: "Submit Project",
      sending: "Sending...",
      thanksTitle: "Thanks. I'll be in touch shortly.",
      thanksNote: "I read every message personally.",
      errorNote: "Something went wrong. Please email me directly.",
    },
    gallery: { images: "images", close: "Close", viewProject: "View project" },
    cartier: CARTIER,
    projects: {
      jaguars: {
        title: "Jaguars & Jewelry",
        titleLines: ["Jaguars", "& Jewelry"],
        category: "Luxury Campaign Concept",
        line: "Power, worn well.",
        intro: "A study in power, elegance and timeless beauty. A conceptual campaign inspired by the world of luxury jewelry and the iconic panther.",
        rail: { lines: ["Instinct", "in a higher", "form"] },
        conceptTitle: ["More than", "a symbol."],
        conceptBody: ["The panther has long represented strength, independence and refined elegance. In this conceptual series, we explore the intersection of nature and high jewelry, where instinct meets craftsmanship."],
        bottomRail: ["Nature", "crafted in", "extraordinary", "detail"],
      },
      pacific: {
        title: "Pacific, 1978",
        titleLines: ["Pacific,", "1978"],
        category: "Architectural Visual Story",
        line: "Architecture as a feeling.",
        intro: "A love letter to the California coast and the architecture of the 1970s. Sun, texture, space and a slower way of living.",
        rail: { lines: ["Timeless", "spaces,", "still relevant"] },
        conceptTitle: ["Architecture", "as a feeling."],
        conceptBody: ["Pacific, 1978 explores the atmosphere of a coastal home through light, materials and everyday moments.", "A visual study of how architecture, nature and lifestyle come together to create a sense of freedom, warmth and timelessness."],
      },
      afterdark: {
        title: "Vintage Party",
        titleLines: ["Vintage", "Party"],
        category: "Editorial Photography",
        line: "Fragments from one night.",
        intro: "An intimate study of nightlife, where elegance, desire and human connection exist in a world of golden light, deep shadows and endless possibility.",
        rail: { lines: ["Same night,", "different", "stories."] },
        conceptTitle: ["Night as", "a canvas."],
        conceptBody: ["Vintage Party captures fragmented moments from a single night: strangers, lovers, rituals and reflections. A visual exploration of atmosphere, intimacy and the timeless allure of nightlife."],
        // indexed by gallery file: g0 toast, g1 piano, g2 red pour, g3 motion,
        // g4 pour, g5 cocktail tray, g6 couple (g7 banquette = unused)
        caps: [
          { n: "06", label: "Celebration", line: "Moments that linger." },
          { n: "05", label: "Sound", line: "A different kind of conversation." },
          { n: "03", label: "Indulgence", line: "Details make the night." },
          { n: "02", label: "Ritual", line: "Motion, light, temptation." },
          { n: "07", label: "Last call", line: "Not an ending, just another story." },
          { n: "01", label: "Arrival", line: "The night begins." },
          { n: "04", label: "Connection", line: "Closer at midnight." },
        ],
      },
      animalprint: {
        title: "Animal Print",
        titleLines: ["Animal", "Print"],
        category: "Fashion Editorial",
        line: "Instinct, indoors.",
        intro: "Wild animals in domestic interiors. A visual exploration of instinct and elegance, where untamed nature meets the familiar, revealing new narratives through texture, contrast and coexistence.",
        rail: { italic: "Patterns with a pulse.", words: ["Nature", "Interiors", "Texture", "Character", "Always", "Welcome"] },
        conceptTitle: ["Instinct,", "indoors."],
        conceptBody: ["These images explore the encounter between the wild and the domestic: animals placed in familiar spaces, not as spectacle, but as presence. A study of texture, attitude and atmosphere, where animal print becomes more than a pattern; a living language."],
        conceptNote: ["Same spaces.", "Different instincts."],
        // indexed by gallery file: g0 leopard, g1 ostrich, g2 peacock, g3 fox
        caps: [
          { n: "02", label: "Comfort", line: "Power looks good here." },
          { n: "05", label: "Attitude", line: "Some guests just don't blend in." },
          { n: "03", label: "Presence", line: "Beauty takes up space." },
          { n: "04", label: "Stillness", line: "Wild at rest." },
        ],
      },
      "hant-xepe-hamiime": {
        title: "HANT · XEPE · HAMÍIME",
        titleLines: ["HANT · XEPE ·", "HAMÍIME"],
        category: "Contemporary visual fiction",
        line: "Earth · Sea · Sky",
        intro: "A contemporary visual series inspired by documented Cmiique Iitom language and Comcaac oral tradition, exploring the boundaries between earth, sea and sky.",
      },
      "under-glass": {
        title: "UNDER GLASS",
        titleLines: ["UNDER", "GLASS"],
        category: "Conceptual Architectural Series",
        line: "Where architecture becomes garden.",
        intro: "A greenhouse imagined as a place to slow down, gather and disappear into nature.",
        rail: { lines: ["Slow down,", "gather,", "disappear"] },
        conceptTitle: ["A landscape,", "not a building."],
        conceptBody: [
          "UNDER GLASS imagines a nursery and café as a landscape rather than a building.",
          "A monumental greenhouse becomes an ecosystem of elevated rooms, suspended paths, water, vegetation and quiet gathering spaces. Architecture recedes into the garden until it becomes difficult to tell where one ends and the other begins.",
          "The project explores a simple idea: what if a café wasn't somewhere you went to consume, but somewhere you went to disconnect and reconnect?",
        ],
        // Subtle, secondary image titles (no descriptive lines) — indexed by
        // gallery order: Exterior, Floating Rooms, Among the Garden, Glass Nest,
        // The Forum, Falling Water, The Bar.
        caps: [
          { n: "01", label: "Exterior" },
          { n: "02", label: "Floating Rooms" },
          { n: "03", label: "Among the Garden" },
          { n: "04", label: "Glass Nest" },
          { n: "05", label: "The Forum" },
          { n: "06", label: "Falling Water" },
          { n: "07", label: "The Bar" },
        ],
      },
    },
    hxh: {
      title: "HANT · XEPE · HAMÍIME",
      subtitle: "Earth · Sea · Sky",
      curatorial:
        "This series does not attempt to recreate Comcaac mythology literally. It begins with documented words, stories and ways of observing the natural world in Cmiique Iitom, then uses them as points of departure for contemporary visual fiction.",
      hero: {
        term: "IIZAX",
        gloss: "Moon · Month",
        body: "In Cmiique Iitom, iizax means both moon and month. Comcaac time was traditionally read through lunar cycles together with stars, animals, plants and seasonal changes. Here, the moon leaves the sky and becomes part of the sea.",
        classification: "Contemporary visual interpretation based on documented Comcaac relationships with lunar cycles.",
      },
      works: {
        azoj: {
          term: "AZOJ",
          gloss: "Star",
          body: "Stars were not simply distant objects in the Comcaac sky. Their appearance, absence and movement helped mark the changing year. This image reverses the heavens: the stars are no longer above the observer, but beneath the surface of the water.",
          classification: "Contemporary visual interpretation based on documented astronomical knowledge.",
        },
        xepe: {
          term: "XEPE",
          gloss: "Sea",
          body: "The sea is central to Comcaac territory, subsistence and oral tradition. Here xepe is imagined not as a horizon to look across, but as a monumental presence occupying the landscape itself.",
          classification: "Contemporary artistic interpretation.",
        },
        hax: {
          term: "HAX",
          gloss: "Fresh water",
          body: "Cmiique Iitom distinguishes hax, fresh water, from xepe, seawater. In an arid landscape shaped by movement between scarce sources of water, this image transforms fresh water into something visibly precious: the spring produces its own light.",
          classification: "Contemporary visual interpretation.",
        },
        azojcpoc: {
          term: "AZOJ CPOC",
          gloss: "The star that falls",
          body: "Cmiique Iitom names the meteor azoj cpoc, literally 'the star that falls.' This image expands that observation into an imagined phenomenon: instead of one falling star, fragments of fire descend from the sky and briefly inhabit the earth.",
          classification: "Contemporary artistic interpretation based on documented language.",
        },
        moosni: {
          term: "MOOSNI",
          gloss: "Sea turtle",
          body: "In a Comcaac creation narrative, moosni descends to the bottom of the primordial sea and returns carrying sand. From the grains she brings back, the earth can exist.",
          classification: "Direct visual interpretation of documented oral tradition.",
        },
        footprint: {
          term: "The ones before",
          gloss: "A trace from an older world",
          body: "Comcaac oral tradition preserves stories of extraordinary beings associated with a distant past. The footprint does not illustrate one specific story; it imagines the landscape retaining evidence of those who came before.",
          classification: "Free visual interpretation inspired by documented oral tradition.",
        },
        hantxepe: {
          term: "HANT · XEPE",
          gloss: "Earth · Sea",
          body: "For the Comcaac, desert and sea are not opposing landscapes but parts of the same inhabited world. This image imagines that relationship literally: the earth opens and reveals the sea continuing beneath it.",
          classification: "Visual interpretation grounded in documented cultural and linguistic context.",
        },
      },
    },
    footer: { descriptor: "Creative Director · Visual Artist", worldwide: "Working worldwide", location: "Ciudad Juárez, Mexico", instagram: "Instagram", email: "Email", privacy: "Privacy", terms: "Terms", shipping: "Shipping" },
    whatsapp: { label: "WhatsApp", cta: "Message on WhatsApp", message: "Hi Luis, I have a project in mind." },
    prints: {
      label: "Prints",
      title: "Limited Fine Art Prints",
      intro: "Selected works from the series, as limited-edition fine-art prints.",
      explore: "Explore prints",
      fromLabel: "From",
      seriesLabel: "Series",
      sizesLabel: "Sizes",
      editionLabel: "Edition",
      edition: "Limited to 25 per size.",
      paperLabel: "Paper",
      paper: "Fine-art giclée on museum-grade paper.",
      coaLabel: "Authenticity",
      coa: "Each print ships with a signed certificate of authenticity.",
      shippingLabel: "Shipping",
      shipping: "Shipping charged separately. Ships worldwide.",
      sizes: [
        { name: "Small", dim: "12 × 18 in", price: "$75" },
        { name: "Medium", dim: "20 × 30 in", price: "$125" },
        { name: "Large", dim: "24 × 36 in", price: "$195" },
      ],
      soon: "Ordering opens once print-quality proofing is approved.",
      inquire: "Ask about this print",
      buy: "Add to cart",
      back: "All prints",
    },
    resources: {
      label: "Resources",
      title: "Resources",
      intro: "Tools, workflows and experiments from my creative practice. Browse freely; unlock the full write-ups with your email.",
      teaserCta: "Explore Resources",
      categories: { agents: "Agents & Automation", tools: "Tools & Open Source", creative: "Creative AI", coding: "Coding with AI" },
      formats: { quick: "Quick Resource", guide: "Guide", playbook: "Playbook" },
      includesLabel: "What's inside",
      lockedLabel: "Email-gated",
      gate: {
        heading: "Unlock this resource",
        body: "Enter your email to read the full resource. One email unlocks the whole library, and you won't be asked again on this device.",
        placeholder: "you@email.com",
        button: "Unlock",
        sending: "Unlocking...",
        invalid: "Please enter a valid email.",
        error: "Something went wrong and the resource stayed locked. Please try again.",
        unavailable: "Sign-up is temporarily unavailable, so this stayed locked. Please try again shortly.",
        draft: "Full write-up in progress. The outline above is what this resource will include; the complete guide is being finalized.",
      },
      items: {
        openmemory: {
          title: "OpenMemory Guide",
          desc: "Persistent memory for AI agents, so they stop forgetting between sessions.",
          includes: ["What OpenMemory is and when to use it", "Install and configuration notes", "How it fits into an agent workflow"],
        },
        "claude-code-setup": {
          title: "My Claude Code Setup",
          desc: "The tools, structure and workflow behind my day-to-day Claude Code setup.",
          includes: ["Structure and the tools I keep", "Workflow and habits", "What changed after real use"],
        },
        openreply: {
          title: "OpenReply",
          desc: "Self-hosted comment-to-DM automation, without an expensive creator SaaS.",
          includes: ["What it is and the cost case", "Install, Railway and the Meta connection", "Real configuration and the gotchas"],
        },
        "ai-visual-workflow": {
          title: "My AI Visual Workflow",
          desc: "Reference, concept, production, selection and refinement, end to end.",
          includes: ["Reference and concept", "Prompting and generation", "Selection and refinement"],
        },
      },
    },
  },
  es: {
    nav: { work: "Trabajo", services: "Servicios", resources: "Recursos", about: "Acerca", contact: "Contacto", menu: "Menú", close: "Cerrar" },
    skipToContent: "Saltar al contenido",
    notFound: {
      eyebrow: "404",
      title: "Esta página no existe.",
      body: "La página que buscas pudo haberse movido o ya no existe.",
      ctaHome: "Volver al inicio",
      ctaWork: "Ver trabajo",
    },
    hero: {
      eyebrow: "Director creativo · Artista visual",
      title: "Dirección creativa y arte visual.",
      sub: "Conceptos visuales, series de imágenes y mundos creativos para marcas, espacios y proyectos culturales, con la IA como una herramienta de producción más.",
      viewWork: "Ver trabajo seleccionado",
      startProject: "Iniciar un proyecto",
    },
    work: { label: "Trabajo seleccionado", indexTitle: "Trabajo seleccionado", indexIntro: "Cuatro mundos visuales. Concepto, dirección de arte e imagen final, desarrollados de principio a fin." },
    projectNav: { prev: "Proyecto anterior", next: "Proyecto siguiente", back: "Volver al trabajo", viewGallery: "Ver galería", project: "Proyecto", scroll: "Desliza para explorar", concept: "El concepto" },
    positioning: {
      title: "No prompts. Dirección creativa.",
      body: "Desarrollo de concepto, dirección de arte, producción visual y una selección cuidadosa, de la primera referencia a la imagen final. La IA es una de las herramientas de producción, no la práctica en sí.",
    },
    services: {
      label: "Servicios",
      title: "Formas de trabajar conmigo.",
      quote: "Cotización a medida",
      cta: "Iniciar un proyecto",
      items: [
        { slug: "custom-visual", inquiry: "visual", secondary: false, name: "Proyectos visuales a medida", desc: "Concepto, dirección creativa y producción visual para marcas, productos y campañas. Puedo desarrollar el concepto desde cero o ejecutar una dirección creativa que ya exista." },
        { slug: "print-creation", inquiry: "print", secondary: false, name: "Creación de obra", desc: "Obra original hecha para un espacio: una pieza, varias o una serie coherente, desarrollada desde tus referencias hasta los archivos finales listos para impresión." },
        { slug: "fine-art-prints", inquiry: "general", secondary: false, name: "Prints de edición limitada", desc: "Obras seleccionadas de las series como prints de edición limitada, 25 por tamaño. Envío por separado." },
        { slug: "web-design", inquiry: "website", secondary: true, name: "Diseño y desarrollo web", desc: "Sitios a medida construidos alrededor de una dirección visual fuerte, estructura clara y una experiencia digital cuidada, del concepto y el diseño hasta la implementación." },
      ],
    },
    about: {
      label: "Acerca",
      body: "Luis Serrano es director creativo y artista visual. Desarrolla conceptos visuales y series de imágenes para marcas, espacios y proyectos culturales, apoyándose en una década en marca y marketing que le da estructura e intención al trabajo. La IA es parte del proceso de producción, no todo el trabajo.",
    },
    contact: {
      title: "¿Tienes algo en mente?",
      sub: "Cuéntame qué estás construyendo.",
      typeLabel: "¿Qué quieres crear?",
      types: { visual: "Proyecto visual a medida", print: "Obra para un espacio", website: "Proyecto web", general: "Algo más" },
      fields: {
        name: "Nombre", email: "Correo", company: "Empresa / Marca",
        assets: "Número de piezas", brief: "¿Qué buscas crear?",
        timeline: "Tiempos", budget: "Presupuesto",
        space: "Espacio / habitación", dimensions: "Dimensiones aprox.",
        needs: "¿Qué necesitas?", websiteUrl: "Sitio actual (si aplica)",
        pageCount: "Número de páginas aprox.", branding: "¿Ya tienes branding / dirección visual?",
        references: "Referencias / enlaces", message: "Mensaje", optional: "opcional",
      },
      opt: { yes: "Sí", no: "No", notSure: "No estoy seguro", select: "Selecciona" },
      submit: "Enviar proyecto",
      sending: "Enviando...",
      thanksTitle: "Gracias. Te contacto muy pronto.",
      thanksNote: "Leo cada mensaje personalmente.",
      errorNote: "Algo salió mal. Escríbeme directamente por correo.",
    },
    gallery: { images: "imágenes", close: "Cerrar", viewProject: "Ver proyecto" },
    cartier: CARTIER,
    projects: {
      jaguars: {
        title: "Jaguars & Jewelry",
        titleLines: ["Jaguars", "& Jewelry"],
        category: "Concepto de campaña de lujo",
        line: "El poder, bien llevado.",
        intro: "Un estudio sobre el poder, la elegancia y la belleza atemporal. Una campaña conceptual inspirada en el mundo de la alta joyería y la icónica pantera.",
        rail: { lines: ["Instinto", "en su forma", "más alta"] },
        conceptTitle: ["Más que", "un símbolo."],
        conceptBody: ["La pantera ha representado durante mucho tiempo la fuerza, la independencia y la elegancia refinada. En esta serie conceptual exploramos el cruce entre la naturaleza y la alta joyería, donde el instinto se encuentra con la artesanía."],
        bottomRail: ["Naturaleza", "labrada con", "un detalle", "extraordinario"],
      },
      pacific: {
        title: "Pacific, 1978",
        titleLines: ["Pacific,", "1978"],
        category: "Historia visual arquitectónica",
        line: "La arquitectura como sensación.",
        intro: "Una carta de amor a la costa de California y a la arquitectura de los años setenta. Sol, textura, espacio y una forma más pausada de vivir.",
        rail: { lines: ["Espacios", "atemporales,", "aún vigentes"] },
        conceptTitle: ["La arquitectura", "como sensación."],
        conceptBody: ["Pacific, 1978 explora la atmósfera de una casa costera a través de la luz, los materiales y los momentos cotidianos.", "Un estudio visual de cómo la arquitectura, la naturaleza y el estilo de vida se unen para crear una sensación de libertad, calidez y atemporalidad."],
      },
      afterdark: {
        title: "Vintage Party",
        titleLines: ["Vintage", "Party"],
        category: "Fotografía editorial",
        line: "Fragmentos de una noche.",
        intro: "Un estudio íntimo de la vida nocturna, donde la elegancia, el deseo y la conexión humana existen en un mundo de luz dorada, sombras profundas y posibilidades infinitas.",
        rail: { lines: ["La misma noche,", "distintas", "historias."] },
        conceptTitle: ["La noche", "como lienzo."],
        conceptBody: ["Vintage Party captura momentos fragmentados de una sola noche: desconocidos, amantes, rituales y reflejos. Una exploración visual de la atmósfera, la intimidad y el encanto atemporal de la vida nocturna."],
        caps: [
          { n: "06", label: "Celebración", line: "Momentos que perduran." },
          { n: "05", label: "Sonido", line: "Otro tipo de conversación." },
          { n: "03", label: "Placer", line: "Los detalles hacen la noche." },
          { n: "02", label: "Ritual", line: "Movimiento, luz, tentación." },
          { n: "07", label: "Última ronda", line: "No es un final, solo otra historia." },
          { n: "01", label: "Llegada", line: "La noche comienza." },
          { n: "04", label: "Conexión", line: "Más cerca a medianoche." },
        ],
      },
      animalprint: {
        title: "Animal Print",
        titleLines: ["Animal", "Print"],
        category: "Editorial de moda",
        line: "Instinto, de puertas adentro.",
        intro: "Animales salvajes en interiores domésticos. Una exploración visual del instinto y la elegancia, donde la naturaleza indómita se encuentra con lo familiar, revelando nuevas narrativas a través de la textura, el contraste y la coexistencia.",
        rail: { italic: "Patrones con pulso.", words: ["Naturaleza", "Interiores", "Textura", "Carácter", "Siempre", "Bienvenidos"] },
        conceptTitle: ["Instinto,", "de puertas adentro."],
        conceptBody: ["Estas imágenes exploran el encuentro entre lo salvaje y lo doméstico: animales colocados en espacios familiares, no como espectáculo, sino como presencia. Un estudio de textura, actitud y atmósfera, donde el animal print se vuelve más que un patrón; un lenguaje vivo."],
        conceptNote: ["Los mismos espacios.", "Distintos instintos."],
        caps: [
          { n: "02", label: "Comodidad", line: "El poder luce bien aquí." },
          { n: "05", label: "Actitud", line: "Algunos invitados no pasan desapercibidos." },
          { n: "03", label: "Presencia", line: "La belleza ocupa espacio." },
          { n: "04", label: "Quietud", line: "Salvaje en reposo." },
        ],
      },
      "hant-xepe-hamiime": {
        title: "HANT · XEPE · HAMÍIME",
        titleLines: ["HANT · XEPE ·", "HAMÍIME"],
        category: "Ficción visual contemporánea",
        line: "Tierra · Mar · Cielo",
        intro: "Una serie visual contemporánea inspirada en la lengua Cmiique Iitom documentada y la tradición oral Comcaac, que explora los límites entre la tierra, el mar y el cielo.",
      },
      "under-glass": {
        title: "UNDER GLASS",
        titleLines: ["UNDER", "GLASS"],
        category: "Serie visual arquitectónica",
        line: "Donde la arquitectura se vuelve jardín.",
        intro: "Un invernadero imaginado como un lugar para bajar el ritmo, reunirse y desaparecer entre la naturaleza.",
        rail: { lines: ["Baja el ritmo,", "reúnete,", "desaparece"] },
        conceptTitle: ["Un paisaje,", "no un edificio."],
        conceptBody: [
          "UNDER GLASS imagina un vivero y café como un paisaje, más que como un edificio.",
          "Un invernadero monumental se convierte en un ecosistema de espacios elevados, caminos suspendidos, agua, vegetación y lugares para reunirse con calma. La arquitectura desaparece poco a poco dentro del jardín, hasta que resulta difícil distinguir dónde termina una y comienza el otro.",
          "El proyecto parte de una idea sencilla: ¿qué pasaría si un café no fuera solamente un lugar para consumir, sino un lugar para desconectarse y volver a conectar?",
        ],
        caps: [
          { n: "01", label: "Exterior" },
          { n: "02", label: "Cuartos flotantes" },
          { n: "03", label: "Entre el jardín" },
          { n: "04", label: "Nido de cristal" },
          { n: "05", label: "El foro" },
          { n: "06", label: "Agua que cae" },
          { n: "07", label: "La barra" },
        ],
      },
    },
    hxh: {
      title: "HANT · XEPE · HAMÍIME",
      subtitle: "Tierra · Mar · Cielo",
      curatorial:
        "Esta serie no intenta recrear literalmente la mitología Comcaac. Parte de palabras, historias y formas documentadas de observar el mundo natural en Cmiique Iitom, y las usa como punto de partida para una ficción visual contemporánea.",
      hero: {
        term: "IIZAX",
        gloss: "Luna · Mes",
        body: "En Cmiique Iitom, iizax significa a la vez luna y mes. El tiempo Comcaac se leía tradicionalmente a través de los ciclos lunares junto con las estrellas, los animales, las plantas y los cambios de estación. Aquí, la luna abandona el cielo y se vuelve parte del mar.",
        classification: "Interpretación visual contemporánea a partir de la relación documentada del pueblo Comcaac con los ciclos lunares.",
      },
      works: {
        azoj: {
          term: "AZOJ",
          gloss: "Estrella",
          body: "Las estrellas no eran simplemente objetos distantes en el cielo Comcaac. Su aparición, su ausencia y su movimiento ayudaban a marcar el cambio del año. Esta imagen invierte el firmamento: las estrellas ya no están sobre quien observa, sino bajo la superficie del agua.",
          classification: "Interpretación visual contemporánea a partir de conocimiento astronómico documentado.",
        },
        xepe: {
          term: "XEPE",
          gloss: "Mar",
          body: "El mar es central para el territorio, la subsistencia y la tradición oral Comcaac. Aquí xepe se imagina no como un horizonte que se mira a lo lejos, sino como una presencia monumental que ocupa el paisaje mismo.",
          classification: "Interpretación artística contemporánea.",
        },
        hax: {
          term: "HAX",
          gloss: "Agua dulce",
          body: "El Cmiique Iitom distingue hax, el agua dulce, de xepe, el agua de mar. En un paisaje árido moldeado por el desplazamiento entre fuentes escasas de agua, esta imagen convierte el agua dulce en algo visiblemente preciado: el manantial produce su propia luz.",
          classification: "Interpretación visual contemporánea.",
        },
        azojcpoc: {
          term: "AZOJ CPOC",
          gloss: "La estrella que cae",
          body: "El Cmiique Iitom nombra al meteoro azoj cpoc, literalmente 'la estrella que cae'. Esta imagen expande esa observación en un fenómeno imaginado: en lugar de una sola estrella fugaz, fragmentos de fuego descienden del cielo y habitan brevemente la tierra.",
          classification: "Interpretación artística contemporánea a partir de lengua documentada.",
        },
        moosni: {
          term: "MOOSNI",
          gloss: "Tortuga marina",
          body: "En un relato Comcaac de la creación, moosni desciende al fondo del mar primordial y regresa cargando arena. De los granos que trae de vuelta, la tierra puede existir.",
          classification: "Interpretación visual directa de tradición oral documentada.",
        },
        footprint: {
          term: "Los que vinieron antes",
          gloss: "Un rastro de un mundo anterior",
          body: "La tradición oral Comcaac conserva historias de seres extraordinarios asociados a un pasado lejano. La huella no ilustra una historia específica; imagina un paisaje que conserva la evidencia de quienes vinieron antes.",
          classification: "Interpretación visual libre inspirada en tradición oral documentada.",
        },
        hantxepe: {
          term: "HANT · XEPE",
          gloss: "Tierra · Mar",
          body: "Para el pueblo Comcaac, el desierto y el mar no son paisajes opuestos, sino partes de un mismo mundo habitado. Esta imagen imagina esa relación de forma literal: la tierra se abre y revela el mar que continúa debajo.",
          classification: "Interpretación visual anclada en un contexto cultural y lingüístico documentado.",
        },
      },
    },
    footer: { descriptor: "Director creativo · Artista visual", worldwide: "Trabajando en todo el mundo", location: "Ciudad Juárez, México", instagram: "Instagram", email: "Correo", privacy: "Privacidad", terms: "Términos", shipping: "Envíos" },
    whatsapp: { label: "WhatsApp", cta: "Escríbeme por WhatsApp", message: "Hola Luis, tengo un proyecto en mente." },
    prints: {
      label: "Prints",
      title: "Prints de edición limitada",
      intro: "Obras seleccionadas de las series, como prints de edición limitada.",
      explore: "Ver prints",
      fromLabel: "Desde",
      seriesLabel: "Serie",
      sizesLabel: "Tamaños",
      editionLabel: "Edición",
      edition: "Edición limitada a 25 por tamaño.",
      paperLabel: "Papel",
      paper: "Giclée fine-art en papel de museo.",
      coaLabel: "Autenticidad",
      coa: "Cada print incluye un certificado de autenticidad firmado.",
      shippingLabel: "Envío",
      shipping: "Envío por separado. Envíos a todo el mundo.",
      sizes: [
        { name: "Chico", dim: "12 × 18 in", price: "$75" },
        { name: "Mediano", dim: "20 × 30 in", price: "$125" },
        { name: "Grande", dim: "24 × 36 in", price: "$195" },
      ],
      soon: "Los pedidos abren cuando se apruebe la prueba de calidad de impresión.",
      inquire: "Preguntar por este print",
      buy: "Agregar al carrito",
      back: "Todos los prints",
    },
    resources: {
      label: "Recursos",
      title: "Recursos",
      intro: "Herramientas, flujos y experimentos de mi práctica creativa. Explora libremente; desbloquea las guías completas con tu correo.",
      teaserCta: "Explorar recursos",
      categories: { agents: "Agentes y automatización", tools: "Herramientas y open source", creative: "IA creativa", coding: "Programar con IA" },
      formats: { quick: "Recurso rápido", guide: "Guía", playbook: "Playbook" },
      includesLabel: "Qué incluye",
      lockedLabel: "Requiere correo",
      gate: {
        heading: "Desbloquea este recurso",
        body: "Escribe tu correo para leer el recurso completo. Un correo desbloquea toda la biblioteca y no te lo pediré de nuevo en este dispositivo.",
        placeholder: "tu@correo.com",
        button: "Desbloquear",
        sending: "Desbloqueando...",
        invalid: "Escribe un correo válido.",
        error: "Algo salió mal y el recurso siguió bloqueado. Intenta de nuevo.",
        unavailable: "El registro no está disponible por ahora, así que esto siguió bloqueado. Intenta de nuevo en un momento.",
        draft: "Guía completa en desarrollo. El resumen de arriba es lo que incluirá este recurso; la guía completa se está terminando.",
      },
      items: {
        openmemory: {
          title: "Guía de OpenMemory",
          desc: "Memoria persistente para agentes de IA, para que dejen de olvidar entre sesiones.",
          includes: ["Qué es OpenMemory y cuándo usarlo", "Notas de instalación y configuración", "Cómo encaja en un flujo con agentes"],
        },
        "claude-code-setup": {
          title: "Mi setup de Claude Code",
          desc: "Las herramientas, la estructura y el flujo detrás de mi Claude Code del día a día.",
          includes: ["Estructura y herramientas que uso", "Flujo y hábitos", "Qué cambió tras el uso real"],
        },
        openreply: {
          title: "OpenReply",
          desc: "Automatización comentario-a-DM autohospedada, sin un SaaS caro para creadores.",
          includes: ["Qué es y el caso de costo", "Instalación, Railway y la conexión con Meta", "Configuración real y los detalles"],
        },
        "ai-visual-workflow": {
          title: "Mi flujo visual con IA",
          desc: "Referencia, concepto, producción, selección y refinamiento, de principio a fin.",
          includes: ["Referencia y concepto", "Prompting y generación", "Selección y refinamiento"],
        },
      },
    },
  },
} as const;

export function getContent(locale: string) {
  return CONTENT[locale === "en" ? "en" : "es"];
}
