export type Locale = "es" | "en";

const CARTIER =
  "Jewels of the Jaguar is an independent, non-commercial artistic project inspired by a Cartier campaign. It was created solely as a creative exploration and portfolio piece and is not commissioned by, affiliated with, or endorsed by Cartier.";

export const CONTENT = {
  en: {
    nav: { work: "Work", services: "Services", resources: "Resources", about: "About", contact: "Contact" },
    hero: {
      eyebrow: "AI + Creative",
      title: "Creative direction, built with AI.",
      sub: "AI-generated visuals, campaign concepts and visual worlds for brands, products and ideas.",
      viewWork: "View Selected Work",
      startProject: "Start a Project",
    },
    work: { label: "Selected Work", indexTitle: "Selected Work", indexIntro: "Four visual worlds. Concept, art direction and final imagery, developed end to end." },
    projectNav: { prev: "Previous project", next: "Next project", back: "Back to work", viewGallery: "View gallery", project: "Project", scroll: "Scroll to explore", concept: "The concept" },
    positioning: {
      title: "Not prompts. Creative direction.",
      body: "AI is used as a production medium to develop visual concepts, campaigns and imagery that would traditionally require much larger productions.",
    },
    services: {
      label: "Services",
      title: "Two ways to work together.",
      sprint: { name: "AI Visual Sprint", price: "From $450", desc: "Creative direction, concept development and roughly six finished visuals, selected and refined." },
      campaign: { name: "AI Campaign Concept", price: "Custom scope", desc: "Editorial worlds and full visual narratives, developed and directed end to end." },
    },
    about: {
      label: "About",
      body: "Luis Serrano is a marketer and creative working at the intersection of AI, visual culture and brand building. His work explores how emerging creative tools can turn ideas into fully realized visual worlds.",
    },
    contact: {
      title: "Have something in mind?",
      sub: "Tell me what you're building.",
      fields: { name: "Name", email: "Email", company: "Company / Brand", assets: "Number of assets", brief: "What are you looking to create?", timeline: "Timeline", budget: "Budget" },
      submit: "Submit Project",
      sending: "Sending...",
      thanksTitle: "Thanks. I'll be in touch shortly.",
      thanksNote: "I read every message personally.",
      errorNote: "Something went wrong. Please email me directly.",
    },
    gallery: { images: "images", close: "Close", viewProject: "View project" },
    cartier: CARTIER,
    projects: {
      jaguars: {
        title: "Jaguars & Jewelry",
        titleLines: ["Jaguars", "& Jewelry"],
        category: "Luxury Campaign Concept",
        line: "Power, worn well.",
        intro: "A study in power, elegance and timeless beauty. A conceptual campaign inspired by the world of luxury jewelry and the iconic panther.",
        rail: { lines: ["Instinct", "in a higher", "form"] },
        conceptTitle: ["More than", "a symbol."],
        conceptBody: ["The panther has long represented strength, independence and refined elegance. In this conceptual series, we explore the intersection of nature and high jewelry, where instinct meets craftsmanship."],
        bottomRail: ["Nature", "crafted in", "extraordinary", "detail"],
      },
      pacific: {
        title: "Pacific, 1978",
        titleLines: ["Pacific,", "1978"],
        category: "Architectural Visual Story",
        line: "Architecture as a feeling.",
        intro: "A love letter to the California coast and the architecture of the 1970s. Sun, texture, space and a slower way of living.",
        rail: { lines: ["Timeless", "spaces,", "still relevant"] },
        conceptTitle: ["Architecture", "as a feeling."],
        conceptBody: ["Pacific, 1978 explores the atmosphere of a coastal home through light, materials and everyday moments.", "A visual study of how architecture, nature and lifestyle come together to create a sense of freedom, warmth and timelessness."],
      },
      afterdark: {
        title: "After Dark",
        titleLines: ["After", "Dark"],
        category: "Editorial Photography",
        line: "Fragments from one night.",
        intro: "An intimate study of nightlife, where elegance, desire and human connection exist in a world of golden light, deep shadows and endless possibility.",
        rail: { lines: ["Same night,", "different", "stories."] },
        conceptTitle: ["Night as", "a canvas."],
        conceptBody: ["After Dark captures fragmented moments from a single night: strangers, lovers, rituals and reflections. A visual exploration of atmosphere, intimacy and the timeless allure of nightlife."],
        // indexed by gallery file: g0 toast, g1 piano, g2 red pour, g3 motion,
        // g4 pour, g5 cocktail tray, g6 couple (g7 banquette = unused)
        caps: [
          { n: "06", label: "Celebration", line: "Moments that linger." },
          { n: "05", label: "Sound", line: "A different kind of conversation." },
          { n: "03", label: "Indulgence", line: "Details make the night." },
          { n: "02", label: "Ritual", line: "Motion, light, temptation." },
          { n: "07", label: "Last call", line: "Not an ending, just another story." },
          { n: "01", label: "Arrival", line: "The night begins." },
          { n: "04", label: "Connection", line: "Closer at midnight." },
        ],
      },
      animalprint: {
        title: "Animal Print",
        titleLines: ["Animal", "Print"],
        category: "Fashion Editorial",
        line: "Instinct, indoors.",
        intro: "Wild animals in domestic interiors. A visual exploration of instinct and elegance, where untamed nature meets the familiar, revealing new narratives through texture, contrast and coexistence.",
        rail: { italic: "Patterns with a pulse.", words: ["Nature", "Interiors", "Texture", "Character", "Always", "Welcome"] },
        conceptTitle: ["Instinct,", "indoors."],
        conceptBody: ["These images explore the encounter between the wild and the domestic: animals placed in familiar spaces, not as spectacle, but as presence. A study of texture, attitude and atmosphere, where animal print becomes more than a pattern; a living language."],
        conceptNote: ["Same spaces.", "Different instincts."],
        // indexed by gallery file: g0 leopard, g1 ostrich, g2 peacock, g3 fox
        caps: [
          { n: "02", label: "Comfort", line: "Power looks good here." },
          { n: "05", label: "Attitude", line: "Some guests just don't blend in." },
          { n: "03", label: "Presence", line: "Beauty takes up space." },
          { n: "04", label: "Stillness", line: "Wild at rest." },
        ],
      },
    },
    footer: { descriptor: "AI + Creative", worldwide: "Working worldwide", location: "Ciudad Juárez, Mexico", instagram: "Instagram", email: "Email" },
    whatsapp: { label: "WhatsApp", cta: "Message on WhatsApp", message: "Hi Luis, I have a project in mind." },
    resources: { label: "Resources", title: "Resources", intro: "Tools, workflows and experiments from my AI creative process.", soon: "Coming soon." },
  },
  es: {
    nav: { work: "Trabajo", services: "Servicios", resources: "Recursos", about: "Acerca", contact: "Contacto" },
    hero: {
      eyebrow: "AI + Creative",
      title: "Dirección creativa, hecha con IA.",
      sub: "Visuales generados con IA, conceptos de campaña y mundos visuales para marcas, productos e ideas.",
      viewWork: "Ver trabajo seleccionado",
      startProject: "Iniciar un proyecto",
    },
    work: { label: "Trabajo seleccionado", indexTitle: "Trabajo seleccionado", indexIntro: "Cuatro mundos visuales. Concepto, dirección de arte e imagen final, desarrollados de principio a fin." },
    projectNav: { prev: "Proyecto anterior", next: "Proyecto siguiente", back: "Volver al trabajo", viewGallery: "Ver galería", project: "Proyecto", scroll: "Desliza para explorar", concept: "El concepto" },
    positioning: {
      title: "No prompts. Dirección creativa.",
      body: "La IA se usa como medio de producción para desarrollar conceptos visuales, campañas e imágenes que tradicionalmente exigirían producciones mucho mayores.",
    },
    services: {
      label: "Servicios",
      title: "Dos formas de trabajar juntos.",
      sprint: { name: "AI Visual Sprint", price: "Desde $450", desc: "Dirección creativa, desarrollo de concepto y alrededor de seis visuales finales, seleccionados y refinados." },
      campaign: { name: "AI Campaign Concept", price: "Alcance a medida", desc: "Mundos editoriales y narrativas visuales completas, desarrolladas y dirigidas de principio a fin." },
    },
    about: {
      label: "Acerca",
      body: "Luis Serrano es mercadólogo y creativo que trabaja en la intersección de la IA, la cultura visual y la construcción de marca. Su trabajo explora cómo las herramientas creativas emergentes convierten ideas en mundos visuales completos.",
    },
    contact: {
      title: "¿Tienes algo en mente?",
      sub: "Cuéntame qué estás construyendo.",
      fields: { name: "Nombre", email: "Correo", company: "Empresa / Marca", assets: "Número de piezas", brief: "¿Qué buscas crear?", timeline: "Tiempos", budget: "Presupuesto" },
      submit: "Enviar proyecto",
      sending: "Enviando...",
      thanksTitle: "Gracias. Te contacto muy pronto.",
      thanksNote: "Leo cada mensaje personalmente.",
      errorNote: "Algo salió mal. Escríbeme directamente por correo.",
    },
    gallery: { images: "imágenes", close: "Cerrar", viewProject: "Ver proyecto" },
    cartier: CARTIER,
    projects: {
      jaguars: {
        title: "Jaguars & Jewelry",
        titleLines: ["Jaguars", "& Jewelry"],
        category: "Concepto de campaña de lujo",
        line: "El poder, bien llevado.",
        intro: "Un estudio sobre el poder, la elegancia y la belleza atemporal. Una campaña conceptual inspirada en el mundo de la alta joyería y la icónica pantera.",
        rail: { lines: ["Instinto", "en su forma", "más alta"] },
        conceptTitle: ["Más que", "un símbolo."],
        conceptBody: ["La pantera ha representado durante mucho tiempo la fuerza, la independencia y la elegancia refinada. En esta serie conceptual exploramos el cruce entre la naturaleza y la alta joyería, donde el instinto se encuentra con la artesanía."],
        bottomRail: ["Naturaleza", "labrada con", "un detalle", "extraordinario"],
      },
      pacific: {
        title: "Pacific, 1978",
        titleLines: ["Pacific,", "1978"],
        category: "Historia visual arquitectónica",
        line: "La arquitectura como sensación.",
        intro: "Una carta de amor a la costa de California y a la arquitectura de los años setenta. Sol, textura, espacio y una forma más pausada de vivir.",
        rail: { lines: ["Espacios", "atemporales,", "aún vigentes"] },
        conceptTitle: ["La arquitectura", "como sensación."],
        conceptBody: ["Pacific, 1978 explora la atmósfera de una casa costera a través de la luz, los materiales y los momentos cotidianos.", "Un estudio visual de cómo la arquitectura, la naturaleza y el estilo de vida se unen para crear una sensación de libertad, calidez y atemporalidad."],
      },
      afterdark: {
        title: "After Dark",
        titleLines: ["After", "Dark"],
        category: "Fotografía editorial",
        line: "Fragmentos de una noche.",
        intro: "Un estudio íntimo de la vida nocturna, donde la elegancia, el deseo y la conexión humana existen en un mundo de luz dorada, sombras profundas y posibilidades infinitas.",
        rail: { lines: ["La misma noche,", "distintas", "historias."] },
        conceptTitle: ["La noche", "como lienzo."],
        conceptBody: ["After Dark captura momentos fragmentados de una sola noche: desconocidos, amantes, rituales y reflejos. Una exploración visual de la atmósfera, la intimidad y el encanto atemporal de la vida nocturna."],
        caps: [
          { n: "06", label: "Celebración", line: "Momentos que perduran." },
          { n: "05", label: "Sonido", line: "Otro tipo de conversación." },
          { n: "03", label: "Placer", line: "Los detalles hacen la noche." },
          { n: "02", label: "Ritual", line: "Movimiento, luz, tentación." },
          { n: "07", label: "Última ronda", line: "No es un final, solo otra historia." },
          { n: "01", label: "Llegada", line: "La noche comienza." },
          { n: "04", label: "Conexión", line: "Más cerca a medianoche." },
        ],
      },
      animalprint: {
        title: "Animal Print",
        titleLines: ["Animal", "Print"],
        category: "Editorial de moda",
        line: "Instinto, de puertas adentro.",
        intro: "Animales salvajes en interiores domésticos. Una exploración visual del instinto y la elegancia, donde la naturaleza indómita se encuentra con lo familiar, revelando nuevas narrativas a través de la textura, el contraste y la coexistencia.",
        rail: { italic: "Patrones con pulso.", words: ["Naturaleza", "Interiores", "Textura", "Carácter", "Siempre", "Bienvenidos"] },
        conceptTitle: ["Instinto,", "de puertas adentro."],
        conceptBody: ["Estas imágenes exploran el encuentro entre lo salvaje y lo doméstico: animales colocados en espacios familiares, no como espectáculo, sino como presencia. Un estudio de textura, actitud y atmósfera, donde el animal print se vuelve más que un patrón; un lenguaje vivo."],
        conceptNote: ["Los mismos espacios.", "Distintos instintos."],
        caps: [
          { n: "02", label: "Comodidad", line: "El poder luce bien aquí." },
          { n: "05", label: "Actitud", line: "Algunos invitados no pasan desapercibidos." },
          { n: "03", label: "Presencia", line: "La belleza ocupa espacio." },
          { n: "04", label: "Quietud", line: "Salvaje en reposo." },
        ],
      },
    },
    footer: { descriptor: "AI + Creative", worldwide: "Trabajando en todo el mundo", location: "Ciudad Juárez, México", instagram: "Instagram", email: "Correo" },
    whatsapp: { label: "WhatsApp", cta: "Escríbeme por WhatsApp", message: "Hola Luis, tengo un proyecto en mente." },
    resources: { label: "Recursos", title: "Recursos", intro: "Herramientas, flujos y experimentos de mi proceso creativo con IA.", soon: "Muy pronto." },
  },
} as const;

export function getContent(locale: string) {
  return CONTENT[locale === "en" ? "en" : "es"];
}
