export interface Country {
  code: string;
  dialCode: string;
  flag: string;
  nameEs: string;
  nameEn: string;
}

export const COUNTRIES: Country[] = [
  // Priority markets first
  { code: "MX", dialCode: "+52", flag: "🇲🇽", nameEs: "México", nameEn: "Mexico" },
  { code: "US", dialCode: "+1", flag: "🇺🇸", nameEs: "Estados Unidos", nameEn: "United States" },
  // Rest alphabetically (ES names)
  { code: "AF", dialCode: "+93", flag: "🇦🇫", nameEs: "Afganistán", nameEn: "Afghanistan" },
  { code: "AL", dialCode: "+355", flag: "🇦🇱", nameEs: "Albania", nameEn: "Albania" },
  { code: "DE", dialCode: "+49", flag: "🇩🇪", nameEs: "Alemania", nameEn: "Germany" },
  { code: "AD", dialCode: "+376", flag: "🇦🇩", nameEs: "Andorra", nameEn: "Andorra" },
  { code: "AO", dialCode: "+244", flag: "🇦🇴", nameEs: "Angola", nameEn: "Angola" },
  { code: "AG", dialCode: "+1-268", flag: "🇦🇬", nameEs: "Antigua y Barbuda", nameEn: "Antigua and Barbuda" },
  { code: "SA", dialCode: "+966", flag: "🇸🇦", nameEs: "Arabia Saudita", nameEn: "Saudi Arabia" },
  { code: "DZ", dialCode: "+213", flag: "🇩🇿", nameEs: "Argelia", nameEn: "Algeria" },
  { code: "AR", dialCode: "+54", flag: "🇦🇷", nameEs: "Argentina", nameEn: "Argentina" },
  { code: "AM", dialCode: "+374", flag: "🇦🇲", nameEs: "Armenia", nameEn: "Armenia" },
  { code: "AU", dialCode: "+61", flag: "🇦🇺", nameEs: "Australia", nameEn: "Australia" },
  { code: "AT", dialCode: "+43", flag: "🇦🇹", nameEs: "Austria", nameEn: "Austria" },
  { code: "AZ", dialCode: "+994", flag: "🇦🇿", nameEs: "Azerbaiyán", nameEn: "Azerbaijan" },
  { code: "BS", dialCode: "+1-242", flag: "🇧🇸", nameEs: "Bahamas", nameEn: "Bahamas" },
  { code: "BH", dialCode: "+973", flag: "🇧🇭", nameEs: "Baréin", nameEn: "Bahrain" },
  { code: "BD", dialCode: "+880", flag: "🇧🇩", nameEs: "Bangladesh", nameEn: "Bangladesh" },
  { code: "BB", dialCode: "+1-246", flag: "🇧🇧", nameEs: "Barbados", nameEn: "Barbados" },
  { code: "BY", dialCode: "+375", flag: "🇧🇾", nameEs: "Bielorrusia", nameEn: "Belarus" },
  { code: "BE", dialCode: "+32", flag: "🇧🇪", nameEs: "Bélgica", nameEn: "Belgium" },
  { code: "BZ", dialCode: "+501", flag: "🇧🇿", nameEs: "Belice", nameEn: "Belize" },
  { code: "BJ", dialCode: "+229", flag: "🇧🇯", nameEs: "Benín", nameEn: "Benin" },
  { code: "BT", dialCode: "+975", flag: "🇧🇹", nameEs: "Bután", nameEn: "Bhutan" },
  { code: "BO", dialCode: "+591", flag: "🇧🇴", nameEs: "Bolivia", nameEn: "Bolivia" },
  { code: "BA", dialCode: "+387", flag: "🇧🇦", nameEs: "Bosnia y Herzegovina", nameEn: "Bosnia and Herzegovina" },
  { code: "BW", dialCode: "+267", flag: "🇧🇼", nameEs: "Botsuana", nameEn: "Botswana" },
  { code: "BR", dialCode: "+55", flag: "🇧🇷", nameEs: "Brasil", nameEn: "Brazil" },
  { code: "BN", dialCode: "+673", flag: "🇧🇳", nameEs: "Brunéi", nameEn: "Brunei" },
  { code: "BG", dialCode: "+359", flag: "🇧🇬", nameEs: "Bulgaria", nameEn: "Bulgaria" },
  { code: "BF", dialCode: "+226", flag: "🇧🇫", nameEs: "Burkina Faso", nameEn: "Burkina Faso" },
  { code: "BI", dialCode: "+257", flag: "🇧🇮", nameEs: "Burundi", nameEn: "Burundi" },
  { code: "CV", dialCode: "+238", flag: "🇨🇻", nameEs: "Cabo Verde", nameEn: "Cape Verde" },
  { code: "KH", dialCode: "+855", flag: "🇰🇭", nameEs: "Camboya", nameEn: "Cambodia" },
  { code: "CM", dialCode: "+237", flag: "🇨🇲", nameEs: "Camerún", nameEn: "Cameroon" },
  { code: "CA", dialCode: "+1", flag: "🇨🇦", nameEs: "Canadá", nameEn: "Canada" },
  { code: "QA", dialCode: "+974", flag: "🇶🇦", nameEs: "Catar", nameEn: "Qatar" },
  { code: "TD", dialCode: "+235", flag: "🇹🇩", nameEs: "Chad", nameEn: "Chad" },
  { code: "CL", dialCode: "+56", flag: "🇨🇱", nameEs: "Chile", nameEn: "Chile" },
  { code: "CN", dialCode: "+86", flag: "🇨🇳", nameEs: "China", nameEn: "China" },
  { code: "CY", dialCode: "+357", flag: "🇨🇾", nameEs: "Chipre", nameEn: "Cyprus" },
  { code: "CO", dialCode: "+57", flag: "🇨🇴", nameEs: "Colombia", nameEn: "Colombia" },
  { code: "KM", dialCode: "+269", flag: "🇰🇲", nameEs: "Comoras", nameEn: "Comoros" },
  { code: "CG", dialCode: "+242", flag: "🇨🇬", nameEs: "Congo", nameEn: "Congo" },
  { code: "CD", dialCode: "+243", flag: "🇨🇩", nameEs: "Congo (RDC)", nameEn: "Congo (DRC)" },
  { code: "KP", dialCode: "+850", flag: "🇰🇵", nameEs: "Corea del Norte", nameEn: "North Korea" },
  { code: "KR", dialCode: "+82", flag: "🇰🇷", nameEs: "Corea del Sur", nameEn: "South Korea" },
  { code: "CR", dialCode: "+506", flag: "🇨🇷", nameEs: "Costa Rica", nameEn: "Costa Rica" },
  { code: "CI", dialCode: "+225", flag: "🇨🇮", nameEs: "Costa de Marfil", nameEn: "Ivory Coast" },
  { code: "HR", dialCode: "+385", flag: "🇭🇷", nameEs: "Croacia", nameEn: "Croatia" },
  { code: "CU", dialCode: "+53", flag: "🇨🇺", nameEs: "Cuba", nameEn: "Cuba" },
  { code: "DK", dialCode: "+45", flag: "🇩🇰", nameEs: "Dinamarca", nameEn: "Denmark" },
  { code: "DJ", dialCode: "+253", flag: "🇩🇯", nameEs: "Yibuti", nameEn: "Djibouti" },
  { code: "DM", dialCode: "+1-767", flag: "🇩🇲", nameEs: "Dominica", nameEn: "Dominica" },
  { code: "EC", dialCode: "+593", flag: "🇪🇨", nameEs: "Ecuador", nameEn: "Ecuador" },
  { code: "EG", dialCode: "+20", flag: "🇪🇬", nameEs: "Egipto", nameEn: "Egypt" },
  { code: "SV", dialCode: "+503", flag: "🇸🇻", nameEs: "El Salvador", nameEn: "El Salvador" },
  { code: "AE", dialCode: "+971", flag: "🇦🇪", nameEs: "Emiratos Árabes Unidos", nameEn: "United Arab Emirates" },
  { code: "ER", dialCode: "+291", flag: "🇪🇷", nameEs: "Eritrea", nameEn: "Eritrea" },
  { code: "SK", dialCode: "+421", flag: "🇸🇰", nameEs: "Eslovaquia", nameEn: "Slovakia" },
  { code: "SI", dialCode: "+386", flag: "🇸🇮", nameEs: "Eslovenia", nameEn: "Slovenia" },
  { code: "ES", dialCode: "+34", flag: "🇪🇸", nameEs: "España", nameEn: "Spain" },
  { code: "EE", dialCode: "+372", flag: "🇪🇪", nameEs: "Estonia", nameEn: "Estonia" },
  { code: "ET", dialCode: "+251", flag: "🇪🇹", nameEs: "Etiopía", nameEn: "Ethiopia" },
  { code: "PH", dialCode: "+63", flag: "🇵🇭", nameEs: "Filipinas", nameEn: "Philippines" },
  { code: "FI", dialCode: "+358", flag: "🇫🇮", nameEs: "Finlandia", nameEn: "Finland" },
  { code: "FJ", dialCode: "+679", flag: "🇫🇯", nameEs: "Fiyi", nameEn: "Fiji" },
  { code: "FR", dialCode: "+33", flag: "🇫🇷", nameEs: "Francia", nameEn: "France" },
  { code: "GA", dialCode: "+241", flag: "🇬🇦", nameEs: "Gabón", nameEn: "Gabon" },
  { code: "GM", dialCode: "+220", flag: "🇬🇲", nameEs: "Gambia", nameEn: "Gambia" },
  { code: "GE", dialCode: "+995", flag: "🇬🇪", nameEs: "Georgia", nameEn: "Georgia" },
  { code: "GH", dialCode: "+233", flag: "🇬🇭", nameEs: "Ghana", nameEn: "Ghana" },
  { code: "GD", dialCode: "+1-473", flag: "🇬🇩", nameEs: "Granada", nameEn: "Grenada" },
  { code: "GR", dialCode: "+30", flag: "🇬🇷", nameEs: "Grecia", nameEn: "Greece" },
  { code: "GT", dialCode: "+502", flag: "🇬🇹", nameEs: "Guatemala", nameEn: "Guatemala" },
  { code: "GN", dialCode: "+224", flag: "🇬🇳", nameEs: "Guinea", nameEn: "Guinea" },
  { code: "GW", dialCode: "+245", flag: "🇬🇼", nameEs: "Guinea-Bisáu", nameEn: "Guinea-Bissau" },
  { code: "GQ", dialCode: "+240", flag: "🇬🇶", nameEs: "Guinea Ecuatorial", nameEn: "Equatorial Guinea" },
  { code: "GY", dialCode: "+592", flag: "🇬🇾", nameEs: "Guyana", nameEn: "Guyana" },
  { code: "HT", dialCode: "+509", flag: "🇭🇹", nameEs: "Haití", nameEn: "Haiti" },
  { code: "HN", dialCode: "+504", flag: "🇭🇳", nameEs: "Honduras", nameEn: "Honduras" },
  { code: "HU", dialCode: "+36", flag: "🇭🇺", nameEs: "Hungría", nameEn: "Hungary" },
  { code: "IN", dialCode: "+91", flag: "🇮🇳", nameEs: "India", nameEn: "India" },
  { code: "ID", dialCode: "+62", flag: "🇮🇩", nameEs: "Indonesia", nameEn: "Indonesia" },
  { code: "IQ", dialCode: "+964", flag: "🇮🇶", nameEs: "Irak", nameEn: "Iraq" },
  { code: "IR", dialCode: "+98", flag: "🇮🇷", nameEs: "Irán", nameEn: "Iran" },
  { code: "IE", dialCode: "+353", flag: "🇮🇪", nameEs: "Irlanda", nameEn: "Ireland" },
  { code: "IS", dialCode: "+354", flag: "🇮🇸", nameEs: "Islandia", nameEn: "Iceland" },
  { code: "IL", dialCode: "+972", flag: "🇮🇱", nameEs: "Israel", nameEn: "Israel" },
  { code: "IT", dialCode: "+39", flag: "🇮🇹", nameEs: "Italia", nameEn: "Italy" },
  { code: "JM", dialCode: "+1-876", flag: "🇯🇲", nameEs: "Jamaica", nameEn: "Jamaica" },
  { code: "JP", dialCode: "+81", flag: "🇯🇵", nameEs: "Japón", nameEn: "Japan" },
  { code: "JO", dialCode: "+962", flag: "🇯🇴", nameEs: "Jordania", nameEn: "Jordan" },
  { code: "KZ", dialCode: "+7", flag: "🇰🇿", nameEs: "Kazajistán", nameEn: "Kazakhstan" },
  { code: "KE", dialCode: "+254", flag: "🇰🇪", nameEs: "Kenia", nameEn: "Kenya" },
  { code: "KG", dialCode: "+996", flag: "🇰🇬", nameEs: "Kirguistán", nameEn: "Kyrgyzstan" },
  { code: "KI", dialCode: "+686", flag: "🇰🇮", nameEs: "Kiribati", nameEn: "Kiribati" },
  { code: "KW", dialCode: "+965", flag: "🇰🇼", nameEs: "Kuwait", nameEn: "Kuwait" },
  { code: "LA", dialCode: "+856", flag: "🇱🇦", nameEs: "Laos", nameEn: "Laos" },
  { code: "LS", dialCode: "+266", flag: "🇱🇸", nameEs: "Lesoto", nameEn: "Lesotho" },
  { code: "LV", dialCode: "+371", flag: "🇱🇻", nameEs: "Letonia", nameEn: "Latvia" },
  { code: "LB", dialCode: "+961", flag: "🇱🇧", nameEs: "Líbano", nameEn: "Lebanon" },
  { code: "LR", dialCode: "+231", flag: "🇱🇷", nameEs: "Liberia", nameEn: "Liberia" },
  { code: "LY", dialCode: "+218", flag: "🇱🇾", nameEs: "Libia", nameEn: "Libya" },
  { code: "LI", dialCode: "+423", flag: "🇱🇮", nameEs: "Liechtenstein", nameEn: "Liechtenstein" },
  { code: "LT", dialCode: "+370", flag: "🇱🇹", nameEs: "Lituania", nameEn: "Lithuania" },
  { code: "LU", dialCode: "+352", flag: "🇱🇺", nameEs: "Luxemburgo", nameEn: "Luxembourg" },
  { code: "MG", dialCode: "+261", flag: "🇲🇬", nameEs: "Madagascar", nameEn: "Madagascar" },
  { code: "MW", dialCode: "+265", flag: "🇲🇼", nameEs: "Malaui", nameEn: "Malawi" },
  { code: "MY", dialCode: "+60", flag: "🇲🇾", nameEs: "Malasia", nameEn: "Malaysia" },
  { code: "MV", dialCode: "+960", flag: "🇲🇻", nameEs: "Maldivas", nameEn: "Maldives" },
  { code: "ML", dialCode: "+223", flag: "🇲🇱", nameEs: "Malí", nameEn: "Mali" },
  { code: "MT", dialCode: "+356", flag: "🇲🇹", nameEs: "Malta", nameEn: "Malta" },
  { code: "MA", dialCode: "+212", flag: "🇲🇦", nameEs: "Marruecos", nameEn: "Morocco" },
  { code: "MU", dialCode: "+230", flag: "🇲🇺", nameEs: "Mauricio", nameEn: "Mauritius" },
  { code: "MR", dialCode: "+222", flag: "🇲🇷", nameEs: "Mauritania", nameEn: "Mauritania" },
  { code: "FM", dialCode: "+691", flag: "🇫🇲", nameEs: "Micronesia", nameEn: "Micronesia" },
  { code: "MD", dialCode: "+373", flag: "🇲🇩", nameEs: "Moldavia", nameEn: "Moldova" },
  { code: "MC", dialCode: "+377", flag: "🇲🇨", nameEs: "Mónaco", nameEn: "Monaco" },
  { code: "MN", dialCode: "+976", flag: "🇲🇳", nameEs: "Mongolia", nameEn: "Mongolia" },
  { code: "ME", dialCode: "+382", flag: "🇲🇪", nameEs: "Montenegro", nameEn: "Montenegro" },
  { code: "MZ", dialCode: "+258", flag: "🇲🇿", nameEs: "Mozambique", nameEn: "Mozambique" },
  { code: "MM", dialCode: "+95", flag: "🇲🇲", nameEs: "Myanmar", nameEn: "Myanmar" },
  { code: "NA", dialCode: "+264", flag: "🇳🇦", nameEs: "Namibia", nameEn: "Namibia" },
  { code: "NR", dialCode: "+674", flag: "🇳🇷", nameEs: "Nauru", nameEn: "Nauru" },
  { code: "NP", dialCode: "+977", flag: "🇳🇵", nameEs: "Nepal", nameEn: "Nepal" },
  { code: "NI", dialCode: "+505", flag: "🇳🇮", nameEs: "Nicaragua", nameEn: "Nicaragua" },
  { code: "NE", dialCode: "+227", flag: "🇳🇪", nameEs: "Níger", nameEn: "Niger" },
  { code: "NG", dialCode: "+234", flag: "🇳🇬", nameEs: "Nigeria", nameEn: "Nigeria" },
  { code: "NO", dialCode: "+47", flag: "🇳🇴", nameEs: "Noruega", nameEn: "Norway" },
  { code: "NZ", dialCode: "+64", flag: "🇳🇿", nameEs: "Nueva Zelanda", nameEn: "New Zealand" },
  { code: "OM", dialCode: "+968", flag: "🇴🇲", nameEs: "Omán", nameEn: "Oman" },
  { code: "PK", dialCode: "+92", flag: "🇵🇰", nameEs: "Pakistán", nameEn: "Pakistan" },
  { code: "PW", dialCode: "+680", flag: "🇵🇼", nameEs: "Palaos", nameEn: "Palau" },
  { code: "PA", dialCode: "+507", flag: "🇵🇦", nameEs: "Panamá", nameEn: "Panama" },
  { code: "PG", dialCode: "+675", flag: "🇵🇬", nameEs: "Papúa Nueva Guinea", nameEn: "Papua New Guinea" },
  { code: "PY", dialCode: "+595", flag: "🇵🇾", nameEs: "Paraguay", nameEn: "Paraguay" },
  { code: "NL", dialCode: "+31", flag: "🇳🇱", nameEs: "Países Bajos", nameEn: "Netherlands" },
  { code: "PE", dialCode: "+51", flag: "🇵🇪", nameEs: "Perú", nameEn: "Peru" },
  { code: "PL", dialCode: "+48", flag: "🇵🇱", nameEs: "Polonia", nameEn: "Poland" },
  { code: "PT", dialCode: "+351", flag: "🇵🇹", nameEs: "Portugal", nameEn: "Portugal" },
  { code: "GB", dialCode: "+44", flag: "🇬🇧", nameEs: "Reino Unido", nameEn: "United Kingdom" },
  { code: "DO", dialCode: "+1-809", flag: "🇩🇴", nameEs: "República Dominicana", nameEn: "Dominican Republic" },
  { code: "CF", dialCode: "+236", flag: "🇨🇫", nameEs: "República Centroafricana", nameEn: "Central African Republic" },
  { code: "CZ", dialCode: "+420", flag: "🇨🇿", nameEs: "República Checa", nameEn: "Czech Republic" },
  { code: "RW", dialCode: "+250", flag: "🇷🇼", nameEs: "Ruanda", nameEn: "Rwanda" },
  { code: "RO", dialCode: "+40", flag: "🇷🇴", nameEs: "Rumanía", nameEn: "Romania" },
  { code: "RU", dialCode: "+7", flag: "🇷🇺", nameEs: "Rusia", nameEn: "Russia" },
  { code: "WS", dialCode: "+685", flag: "🇼🇸", nameEs: "Samoa", nameEn: "Samoa" },
  { code: "KN", dialCode: "+1-869", flag: "🇰🇳", nameEs: "San Cristóbal y Nieves", nameEn: "Saint Kitts and Nevis" },
  { code: "SM", dialCode: "+378", flag: "🇸🇲", nameEs: "San Marino", nameEn: "San Marino" },
  { code: "VC", dialCode: "+1-784", flag: "🇻🇨", nameEs: "San Vicente y las Granadinas", nameEn: "Saint Vincent and the Grenadines" },
  { code: "LC", dialCode: "+1-758", flag: "🇱🇨", nameEs: "Santa Lucía", nameEn: "Saint Lucia" },
  { code: "ST", dialCode: "+239", flag: "🇸🇹", nameEs: "Santo Tomé y Príncipe", nameEn: "Sao Tome and Principe" },
  { code: "SN", dialCode: "+221", flag: "🇸🇳", nameEs: "Senegal", nameEn: "Senegal" },
  { code: "RS", dialCode: "+381", flag: "🇷🇸", nameEs: "Serbia", nameEn: "Serbia" },
  { code: "SC", dialCode: "+248", flag: "🇸🇨", nameEs: "Seychelles", nameEn: "Seychelles" },
  { code: "SL", dialCode: "+232", flag: "🇸🇱", nameEs: "Sierra Leona", nameEn: "Sierra Leone" },
  { code: "SG", dialCode: "+65", flag: "🇸🇬", nameEs: "Singapur", nameEn: "Singapore" },
  { code: "SY", dialCode: "+963", flag: "🇸🇾", nameEs: "Siria", nameEn: "Syria" },
  { code: "SO", dialCode: "+252", flag: "🇸🇴", nameEs: "Somalia", nameEn: "Somalia" },
  { code: "LK", dialCode: "+94", flag: "🇱🇰", nameEs: "Sri Lanka", nameEn: "Sri Lanka" },
  { code: "ZA", dialCode: "+27", flag: "🇿🇦", nameEs: "Sudáfrica", nameEn: "South Africa" },
  { code: "SD", dialCode: "+249", flag: "🇸🇩", nameEs: "Sudán", nameEn: "Sudan" },
  { code: "SS", dialCode: "+211", flag: "🇸🇸", nameEs: "Sudán del Sur", nameEn: "South Sudan" },
  { code: "SE", dialCode: "+46", flag: "🇸🇪", nameEs: "Suecia", nameEn: "Sweden" },
  { code: "CH", dialCode: "+41", flag: "🇨🇭", nameEs: "Suiza", nameEn: "Switzerland" },
  { code: "SR", dialCode: "+597", flag: "🇸🇷", nameEs: "Surinam", nameEn: "Suriname" },
  { code: "SZ", dialCode: "+268", flag: "🇸🇿", nameEs: "Suazilandia", nameEn: "Eswatini" },
  { code: "TJ", dialCode: "+992", flag: "🇹🇯", nameEs: "Tayikistán", nameEn: "Tajikistan" },
  { code: "TZ", dialCode: "+255", flag: "🇹🇿", nameEs: "Tanzania", nameEn: "Tanzania" },
  { code: "TH", dialCode: "+66", flag: "🇹🇭", nameEs: "Tailandia", nameEn: "Thailand" },
  { code: "TL", dialCode: "+670", flag: "🇹🇱", nameEs: "Timor Oriental", nameEn: "Timor-Leste" },
  { code: "TG", dialCode: "+228", flag: "🇹🇬", nameEs: "Togo", nameEn: "Togo" },
  { code: "TO", dialCode: "+676", flag: "🇹🇴", nameEs: "Tonga", nameEn: "Tonga" },
  { code: "TT", dialCode: "+1-868", flag: "🇹🇹", nameEs: "Trinidad y Tobago", nameEn: "Trinidad and Tobago" },
  { code: "TN", dialCode: "+216", flag: "🇹🇳", nameEs: "Túnez", nameEn: "Tunisia" },
  { code: "TM", dialCode: "+993", flag: "🇹🇲", nameEs: "Turkmenistán", nameEn: "Turkmenistan" },
  { code: "TR", dialCode: "+90", flag: "🇹🇷", nameEs: "Turquía", nameEn: "Turkey" },
  { code: "TV", dialCode: "+688", flag: "🇹🇻", nameEs: "Tuvalu", nameEn: "Tuvalu" },
  { code: "UA", dialCode: "+380", flag: "🇺🇦", nameEs: "Ucrania", nameEn: "Ukraine" },
  { code: "UG", dialCode: "+256", flag: "🇺🇬", nameEs: "Uganda", nameEn: "Uganda" },
  { code: "UY", dialCode: "+598", flag: "🇺🇾", nameEs: "Uruguay", nameEn: "Uruguay" },
  { code: "UZ", dialCode: "+998", flag: "🇺🇿", nameEs: "Uzbekistán", nameEn: "Uzbekistan" },
  { code: "VU", dialCode: "+678", flag: "🇻🇺", nameEs: "Vanuatu", nameEn: "Vanuatu" },
  { code: "VA", dialCode: "+379", flag: "🇻🇦", nameEs: "Vaticano", nameEn: "Vatican City" },
  { code: "VE", dialCode: "+58", flag: "🇻🇪", nameEs: "Venezuela", nameEn: "Venezuela" },
  { code: "VN", dialCode: "+84", flag: "🇻🇳", nameEs: "Vietnam", nameEn: "Vietnam" },
  { code: "YE", dialCode: "+967", flag: "🇾🇪", nameEs: "Yemen", nameEn: "Yemen" },
  { code: "ZM", dialCode: "+260", flag: "🇿🇲", nameEs: "Zambia", nameEn: "Zambia" },
  { code: "ZW", dialCode: "+263", flag: "🇿🇼", nameEs: "Zimbabue", nameEn: "Zimbabwe" },
];
